### ISSUE TITLE
add files to svn

### ISSUE THREAD

**Issue by DullGame** [consulo/consulo-apache-subversion#1]
I checked out a project (empty) from remote svn server, but then I can't find any button to add files to svn. (like git add), the cvs menu didn't change. but .svn folder is created.

**Comment by VISTALL** [comment]
![](http://klikr.org/d662329ae14fff381074547eb203.png)

**Comment by VISTALL** [comment]
show pls this menu

**Comment by DullGame** [comment]
![bug](https://cloud.githubusercontent.com/assets/10781622/5987115/91d67e2a-a955-11e4-8888-34a94a88b84e.jpg)

**Comment by DullGame** [comment]
svn version 1.8

**Comment by VISTALL** [comment]
VCS -Enable Version Control - SVN

**Comment by VISTALL** [comment]
i dont tested but thnk that svn 1.8 not supported

**Comment by VISTALL** [comment]
![vcs](https://cloud.githubusercontent.com/assets/542934/5987281/ce027fe8-a932-11e4-9564-fc59eb21b323.gif)

**Comment by DullGame** [comment]
there's no enable version control button.
I deleted the project folder .consulo and recreated it, then everything went well.(do u want to see my old .consulo folder?)
It seems ok with svn 1.8.
but commit failed with this error:

**Comment by DullGame** [comment]
there's no enable version control button.
I deleted the project folder .consulo and recreated it, then everything went well.(do u want to see my old .consulo folder?)
It seems ok with svn 1.8.
but commit failed with this error:

![bug](https://cloud.githubusercontent.com/assets/10781622/5987343/4ed0b744-a95f-11e4-9114-fd99f2d4a1e8.jpg)

**Comment by VISTALL** [comment]
yep - 1.8 problem, need merge. Sorry but at current time, i cant do it

**Comment by DullGame** [comment]
take your time :)

**Comment by VISTALL** [comment]
https://github.com/consulo/consulo-apache-subversion/issues/2
