### ISSUE TITLE
Visual problems in SVN settings

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-apache-subversion#1]
There're 2 minor visual problems in SSH Settings of Subversion plugin:
![svn_ssh_settings_visual_artifacts](https://user-images.githubusercontent.com/16825982/27440610-f1c2b9a6-5773-11e7-9076-a2f4a78948da.png)

1. Numeric input of Port doesn't support scaling (actually it's relevant for all numeric inputs on other tabs of SVN configuration).
2. Radio button for Password is incorrectly placed.

One more minor request: now Subversion plugin cannot be found via plugin search if you type "SVN" (common abbreviation for Subversion). Please include this abbreviation into plugin description so it could be found.

**Comment by VISTALL** [comment]
Without HiDPI this bug look more funny


![](http://klikr.org/dde79f3d7247aa4611d1bec10a57.gif)

**Comment by VISTALL** [comment]
input bug extracted https://github.com/consulo/consulo/issues/288

**Comment by unv-unv** [comment]
Fixed after last update - thanks. Though dot inside selected radio-button still a bit off-centered in 200% scale.

**Comment by VISTALL** [comment]
extracted https://github.com/consulo/consulo/issues/289

**Comment by VISTALL** [comment]
fixed
