### ISSUE TITLE
When scrolling diff to the bottom, line numbers scroll incorrectly

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-apache-subversion#3]
Line numbers stop correctly scrolling when I scroll diff to the very bottom and produce visual artifacts:
![svn_diff_line_numbers_incorrectly_scroll_at_the_bottom](https://user-images.githubusercontent.com/16825982/27712500-fee23a50-5d2f-11e7-8a20-f18490e68e99.png)

**Comment by VISTALL** [comment]
Looks like platform bug

![](http://klikr.org/c2458d6110fb9973826c73276a73.png)


$moveto consulo
